[package]
name = "live-01"
version = "0.1.0"
authors = ["AreebSiddiqui <areeb40@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
